import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Theme, Title } from '../src/@types/app'

import { useAppContext } from '../src/context/useAppContext'

// Components
import { Header } from '../src/components/Header/Header'
import { TaskForm } from '../src/components/Forms/TaskForm'
import { Sidebar } from '../src/components/Sidebar/Sidebar'

const Home: NextPage = () => {
  // const [theme, setTheme] = useState<Theme>('dark')
  const [workspaceTitle, setWorkspaceTitle] = useState<Title>('new project') // TODO add character limit
  const [isMobile, setIsMobile] = useState<boolean>(true)
  let { kanban, toggleTheme, theme } = useAppContext()

  console.log(theme)
  // let toggleTheme = () => {
  //   setTheme((curTheme) => (curTheme == 'dark' ? 'light' : 'dark'))
  // }

  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth < 575) {
        setIsMobile(true)
      } else {
        setIsMobile(false)
      }
    }
    handleResize()
    window.addEventListener('resize', handleResize)

    return () => {
      window.removeEventListener('resize', handleResize)
    }
  }, [])

  return (
    <div className="" style={{ position: 'relative' }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header theme={theme} title={workspaceTitle} isMobile={isMobile} />
      </header>
      <Sidebar isMobile={isMobile} theme={theme} toggleTheme={toggleTheme} />
    </div>
  )
}

export default Home

// <div>
//   <TaskForm theme={theme} />
// </div>
